server:
  port: 7777
  servlet:
    context-path: /scala-boot
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zhk
    password:
    url: jdbc:mysql://zhk-linux:3306/imooc_log?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Hongkong
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql